# Generated by Django 4.2.7 on 2023-11-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link to Continue Reading...', max_length=255),
        ),
    ]
